# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  SYSTEMD_PATH: tmp/systemd
  MAN_FILES:
    - systemd.automount
    - systemd.device
    - systemd.mount
    - systemd.path
    - systemd.scope
    - systemd.service
    - systemd.slice
    - systemd.socket
    - systemd.swap
    - systemd.timer
    - systemd.target
    - systemd.unit
  SHARED_MAN_FILES:
    - systemd.exec
    - systemd.kill
    - systemd.resource-control

env:
  PIP: .venv/bin/pip
  PYTHON: .venv/bin/python3

tasks:
  default:
    cmds:
      - go run .

  clone-or-pull-systemd:
    desc: Clone systemd repo if it doesn't exist, otherwise pull latest changes
    cmds:
      - |
        if [ -d "{{.SYSTEMD_PATH}}" ]; then
          cd {{.SYSTEMD_PATH}} && git pull
        else
          git clone https://github.com/systemd/systemd {{.SYSTEMD_PATH}}
        fi

  gen:
    deps:
      - setup-python
      - clone-or-pull-systemd
    cmds:
      - task: gen-files

  gen-files:
    internal: true
    deps:
      - for:
          var: MAN_FILES
        task: gen-file
        vars:
          MAN: "{{ .ITEM }}"
    cmds:
      - gofmt -w .

  gen-file:
    internal: true
    vars:
      SHARED_MAN_FLAGS: '{{range .SHARED_MAN_FILES}}--shared-man {{.}} {{end}}'
    cmds:
      - $PYTHON -m scripts.gen --man {{.MAN}} {{.SHARED_MAN_FLAGS}} --log-level error > ./configs/{{.MAN}}.go

  test-gen:
    desc: Verify that scripts/gen produces identical output for the current systemd version
    deps:
      - clone-or-pull-systemd
    cmds:
      - mkdir -p tmp/test-gen
      - defer: rm -rf tmp/test-gen
      - for:
          var: MAN_FILES
        task: test-gen-file
        vars:
          MAN: "{{ .ITEM }}"

  test-gen-file:
    internal: true
    vars:
      SHARED_MAN_FLAGS: '{{range .SHARED_MAN_FILES}}--shared-man {{.}} {{end}}'
    cmds:
      - cmd: $PYTHON -m scripts.gen --man {{.MAN}} {{.SHARED_MAN_FLAGS}} --log-level error | gofmt > tmp/test-gen/{{.MAN}}.go
        silent: true
      - diff -u ./configs/{{.MAN}}.go tmp/test-gen/{{.MAN}}.go

  setup-python:
    desc: Set up Python venv in .venv and install dependencies
    cmds:
      - python3 -m venv .venv
      - $PIP install --upgrade pip
      - $PIP install -r requirements.txt
    sources:
      - requirements.txt
