# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  SYSTEMD_PATH: tmp/systemd
  MAN_FILES:
    - systemd.automount
    - systemd.device
    - systemd.mount
    - systemd.path
    - systemd.scope
    - systemd.service
    - systemd.slice
    - systemd.socket
    - systemd.swap
    - systemd.timer
    - systemd.target
    - systemd.unit

env:
  PIP: .venv/bin/pip
  PYTHON: .venv/bin/python3

tasks:
  default:
    cmds:
      - go run .

  clone-or-pull-systemd:
    desc: Clone systemd repo if it doesn't exist, otherwise pull latest changes
    cmds:
      - |
        if [ -d "{{.SYSTEMD_PATH}}" ]; then
          cd {{.SYSTEMD_PATH}} && git pull
        else
          git clone https://github.com/systemd/systemd {{.SYSTEMD_PATH}}
        fi

  gen:
    deps:
      - clone-or-pull-systemd
    cmds:
      - mkdir -p tmp
      - mkdir -p ./tmp/gperf

      - task: extract-gperfs
      - $PYTHON scripts/extract_parser_types.py "{{.SYSTEMD_PATH}}" ./tmp/gperf/parser_type.jsonl ./tmp/gperf
      - task: gen-files

  gen-files:
    internal: true
    deps:
      - for:
          var: MAN_FILES
        task: gen-file
        vars:
          MAN: "{{ .ITEM }}"
    cmds:
      - gofmt -w .

  gen-file:
    internal: true
    cmds:
      - go run ./cmd/gen --man {{.MAN}} --shared-man systemd.exec --shared-man systemd.kill --shared-man systemd.resource-control > ./configs/{{.MAN}}.go

  test-gen:
    desc: Verify that cmd/gen produces identical output for the current systemd version
    deps:
      - clone-or-pull-systemd
    cmds:
      - mkdir -p tmp/test-gen
      - defer: rm -rf tmp/test-gen
      - task: extract-gperfs
      - $PYTHON scripts/extract_parser_types.py "{{.SYSTEMD_PATH}}" ./tmp/gperf/parser_type.jsonl ./tmp/gperf
      - for:
          var: MAN_FILES
        task: test-gen-file
        vars:
          MAN: "{{ .ITEM }}"

  test-gen-file:
    internal: true
    cmds:
      - cmd: go run ./cmd/gen --log-level error --man {{.MAN}} --shared-man systemd.exec --shared-man systemd.kill --shared-man systemd.resource-control | gofmt > tmp/test-gen/{{.MAN}}.go
        silent: true
      - diff -u ./configs/{{.MAN}}.go tmp/test-gen/{{.MAN}}.go

  extract-gperfs:
    internal: true
    silent: true
    vars:
      FILES:
        sh: find tmp/systemd/src -type f \( -name '*.gperf' -o -name '*.gperf.in' \)
    deps:
      - for:
          var: FILES
        task: extract-gperf
        vars:
          ITEM: "{{.ITEM}}"

  extract-gperf:
    internal: true
    silent: true
    cmds:
      - ./scripts/extract_gperf.sh "{{.ITEM}}" "./tmp/gperf"
  
  setup-python:
    desc: Set up Python venv in .venv and install dependencies
    cmds:
      - python3 -m venv .venv
      - $PIP install --upgrade pip
      - $PIP install -r requirements.txt
    sources:
      - requirements.txt
