// Code generated by scripts/gen; DO NOT EDIT.

package configs

import (
	"strings"
)

// UnitSource indicates where a known unit name comes from.
type UnitSource string

const (
	// UnitSourceSpecial marks units defined in systemd.special(7).
	UnitSourceSpecial UnitSource = "special"
	// UnitSourceShipped marks units shipped with the systemd distribution.
	UnitSourceShipped UnitSource = "shipped"
	// UnitSourceUser marks units defined by user HCL configuration.
	UnitSourceUser UnitSource = "user"
)

// KnownUnit represents a well-known systemd unit name.
type KnownUnit struct {
	Name       string
	UnitType   string
	IsTemplate bool
	Source     UnitSource
}

// DefaultKnownUnits contains all well-known systemd unit names
// from systemd.special(7) and the shipped unit files.
var DefaultKnownUnits = []KnownUnit{
	{Name: "-.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "-.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "app.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "background.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "basic.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "blockdev@.target", UnitType: "target", IsTemplate: true, Source: UnitSourceSpecial},
	{Name: "bluetooth.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "boot-complete.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "breakpoint-pre-basic.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "breakpoint-pre-mount.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "breakpoint-pre-switch-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "breakpoint-pre-udev.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "capsule.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "capsule@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "capsule@.target", UnitType: "target", IsTemplate: true, Source: UnitSourceSpecial},
	{Name: "console-getty.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "container-getty@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "cryptsetup-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "cryptsetup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "ctrl-alt-del.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "dbus.service", UnitType: "service", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "dbus.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "debug-shell.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "default.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "dev-hugepages.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "dev-mqueue.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "display-manager.service", UnitType: "service", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "emergency.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "emergency.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "exit.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "factory-reset-now.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "factory-reset.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "final.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "first-boot-complete.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "getty-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "getty.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "getty@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "graphical-session-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "graphical-session.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "graphical.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "halt.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "hibernate.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "hybrid-sleep.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "imports-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "imports.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "init.scope", UnitType: "scope", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "initrd-cleanup.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "initrd-fs.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "initrd-parse-etc.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "initrd-root-device.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "initrd-root-fs.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "initrd-switch-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "initrd-switch-root.target", UnitType: "target", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "initrd-udevadm-cleanup-db.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "initrd-usr-fs.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "initrd.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "integritysetup-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "integritysetup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "kbrequest.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "kexec.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "kmod-static-nodes.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "ldconfig.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "local-fs-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "local-fs.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "machine.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "machines.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "modprobe@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "multi-user.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "network-online.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "network-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "network.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "nss-lookup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "nss-user-lookup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "paths.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "poweroff.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "printer.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "proc-sys-fs-binfmt_misc.automount", UnitType: "automount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "proc-sys-fs-binfmt_misc.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "quotaon-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "quotaon@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "reboot.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "remote-cryptsetup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "remote-fs-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "remote-fs.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "remote-integritysetup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "remote-veritysetup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "rescue.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "rescue.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "rpcbind.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "serial-getty@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "session.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "shutdown.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "sigpwr.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "sleep.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "slices.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "smartcard.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "sockets.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "soft-reboot.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "sound.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "ssh-access.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "storage-target-mode.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "suspend-then-hibernate.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "suspend.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "swap.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "sys-fs-fuse-connections.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "sys-kernel-config.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "sys-kernel-debug.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "sys-kernel-tracing.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "sysinit.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "syslog.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "system-systemd\x2dcryptsetup.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "system-systemd\x2dmute\x2dconsole.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "system-systemd\x2dveritysetup.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "system-update-cleanup.service", UnitType: "service", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "system-update-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "system-update.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "system.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "systemd-ask-password-console.path", UnitType: "path", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-ask-password-console.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-ask-password-wall.path", UnitType: "path", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-ask-password-wall.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-ask-password.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-ask-password@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-backlight@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-battery-check.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-binfmt.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-bless-boot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-boot-check-no-failures.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-boot-clear-sysfail.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-boot-random-seed.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-boot-update.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-bootctl.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-bootctl@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-bsod.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-confext-initrd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-confext-sysroot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-confext.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-coredump.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-coredump@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-creds.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-creds@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-exit.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-factory-reset-complete.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-factory-reset-reboot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-factory-reset-request.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-factory-reset.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-factory-reset@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-firstboot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-fsck-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-fsck@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-growfs-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-growfs@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-halt.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hibernate-clear.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hibernate-resume.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hibernate.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-homed-activate.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-homed-firstboot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-homed.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hostnamed.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hostnamed.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hwdb-update.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-hybrid-sleep.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-imds-early-network.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-imds-import.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-imdsd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-imdsd@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-importd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-importd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-catalog-update.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-flush.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-gatewayd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-gatewayd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-remote.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-remote.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journal-upload.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journalctl.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journalctl@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-journald-audit.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journald-dev-log.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journald-sync@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-journald-varlink@.socket", UnitType: "socket", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-journald.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journald.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-journald@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-journald@.socket", UnitType: "socket", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-kexec.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-localed.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-logind-varlink.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-logind.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-loop@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-machine-id-commit.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-machined.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-machined.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-modules-load.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-mountfsd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-mountfsd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-mute-console.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-mute-console@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-network-generator.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd-persistent-storage.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd-resolve-hook.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd-varlink-metrics.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd-varlink.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd-wait-online.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd-wait-online@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-networkd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-networkd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-nspawn@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-nsresourced.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-nsresourced.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-oomd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-oomd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrextend.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrextend@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-pcrfs-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrfs@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-file-system.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-firmware-code.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-firmware-config.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-machine-id.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-make-policy.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-secureboot-authority.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock-secureboot-policy.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrlock@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-pcrmachine.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrnvdone.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrosseparator.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrphase-factory-reset.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrphase-initrd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrphase-storage-target-mode.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrphase-sysinit.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrphase.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pcrproduct.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-portabled.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-poweroff.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-pstore.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-quotacheck-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-quotacheck@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-random-seed.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-reboot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-remount-fs.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-repart.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-repart.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-repart@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-report-basic.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-report-basic@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-report-cgroup.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-report-cgroup@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-resolved-monitor.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-resolved-varlink.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-resolved.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-rfkill.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-rfkill.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-soft-reboot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-storagetm.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-suspend-then-hibernate.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-suspend.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysctl.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysext-initrd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysext-sysroot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysext.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysext.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysext@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-sysupdate-reboot.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysupdate-reboot.timer", UnitType: "timer", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysupdate.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysupdate.timer", UnitType: "timer", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysupdated.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-sysusers.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-time-wait-sync.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-timedated.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-timesyncd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tmpfiles-clean.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tmpfiles-clean.timer", UnitType: "timer", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tmpfiles-setup-dev-early.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tmpfiles-setup-dev.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tmpfiles-setup.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tpm2-clear.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tpm2-setup-early.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tpm2-setup.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-tpm2-swtpm.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udev-load-credentials.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udev-settle.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udev-trigger.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udevd-control.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udevd-kernel.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udevd-varlink.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-udevd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-update-done.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-update-utmp.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-user-sessions.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-userdb-load-credentials.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-userdbd.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-userdbd.socket", UnitType: "socket", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-validatefs@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-vconsole-setup.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "systemd-vmspawn@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "systemd-volatile-root.service", UnitType: "service", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "time-set.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "time-sync.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "timers.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "tmp.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "tpm2.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "umount.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "usb-gadget.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "user-runtime-dir@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "user.slice", UnitType: "slice", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "user@.service", UnitType: "service", IsTemplate: true, Source: UnitSourceShipped},
	{Name: "var-lib-machines.mount", UnitType: "mount", IsTemplate: false, Source: UnitSourceShipped},
	{Name: "veritysetup-pre.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "veritysetup.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
	{Name: "xdg-desktop-autostart.target", UnitType: "target", IsTemplate: false, Source: UnitSourceSpecial},
}

// KnownUnitsIndex provides fast lookup of known unit names.
type KnownUnitsIndex struct {
	byName    map[string]KnownUnit
	byType    map[string][]KnownUnit
	templates map[string]KnownUnit // key is template prefix, e.g. "getty@"
}

// NewKnownUnitsIndex builds an index from a slice of KnownUnit.
func NewKnownUnitsIndex(units []KnownUnit) KnownUnitsIndex {
	idx := KnownUnitsIndex{
		byName:    make(map[string]KnownUnit, len(units)),
		byType:    make(map[string][]KnownUnit),
		templates: make(map[string]KnownUnit),
	}
	for _, u := range units {
		idx.byName[u.Name] = u
		idx.byType[u.UnitType] = append(idx.byType[u.UnitType], u)
		if u.IsTemplate {
			// Store e.g. "getty@" for "getty@.service"
			if at := strings.Index(u.Name, "@"); at >= 0 {
				dot := strings.LastIndex(u.Name, ".")
				if dot > at {
					prefix := u.Name[:at+1]
					suffix := u.Name[dot:]
					idx.templates[prefix+suffix] = u
				}
			}
		}
	}
	return idx
}

// Contains returns true if name is a known unit or matches a template.
// For example, "getty@tty1.service" matches the template "getty@.service".
func (idx KnownUnitsIndex) Contains(name string) bool {
	if _, ok := idx.byName[name]; ok {
		return true
	}
	return idx.MatchesTemplate(name)
}

// MatchesTemplate returns true if name is an instance of a known template unit.
// E.g. "getty@tty1.service" matches template "getty@.service".
func (idx KnownUnitsIndex) MatchesTemplate(name string) bool {
	at := strings.Index(name, "@")
	if at < 0 {
		return false
	}
	dot := strings.LastIndex(name, ".")
	if dot <= at {
		return false
	}
	key := name[:at+1] + name[dot:]
	_, ok := idx.templates[key]
	return ok
}

// ByType returns all known units of the given type (e.g. "target", "service").
func (idx KnownUnitsIndex) ByType(unitType string) []KnownUnit {
	return idx.byType[unitType]
}

// MergeKnownUnits creates an index from default units plus additional user-defined units.
func MergeKnownUnits(defaults []KnownUnit, extra ...KnownUnit) KnownUnitsIndex {
	all := make([]KnownUnit, 0, len(defaults)+len(extra))
	all = append(all, defaults...)
	all = append(all, extra...)
	return NewKnownUnitsIndex(all)
}
