package configs

import (
	"github.com/hashicorp/hcl/v2"
	"os"
)

type InstallBlock struct {
	Alias           string `hcl:"alias,optional" systemd:"Alias"`
	Also            string `hcl:"also,optional" systemd:"Also"`
	DefaultInstance string `hcl:"default_instance,optional" systemd:"DefaultInstance"`
	RequiredBy      string `hcl:"required_by,optional" systemd:"RequiredBy"`
	UpheldBy        string `hcl:"upheld_by,optional" systemd:"UpheldBy"`
	WantedBy        string `hcl:"wanted_by,optional" systemd:"WantedBy"`
}

type UnitBlock struct {
	After                           []hcl.Traversal `unitd:"after,optional" systemd:"After"`
	AllowIsolate                    bool            `hcl:"allow_isolate,optional" systemd:"AllowIsolate"`
	AssertACPower                   string          `hcl:"assert_ac_power,optional" systemd:"AssertACPower"`
	AssertArchitecture              string          `hcl:"assert_architecture,optional" systemd:"AssertArchitecture"`
	AssertCPUFeature                string          `hcl:"assert_cpu_feature,optional" systemd:"AssertCPUFeature"`
	AssertCPUPressure               string          `hcl:"assert_cpu_pressure,optional" systemd:"AssertCPUPressure"`
	AssertCPUs                      string          `hcl:"assert_cp_us,optional" systemd:"AssertCPUs"`
	AssertCapability                string          `hcl:"assert_capability,optional" systemd:"AssertCapability"`
	AssertControlGroupController    string          `hcl:"assert_control_group_controller,optional" systemd:"AssertControlGroupController"`
	AssertCredential                string          `hcl:"assert_credential,optional" systemd:"AssertCredential"`
	AssertDirectoryNotEmpty         string          `hcl:"assert_directory_not_empty,optional" systemd:"AssertDirectoryNotEmpty"`
	AssertEnvironment               string          `hcl:"assert_environment,optional" systemd:"AssertEnvironment"`
	AssertFileIsExecutable          string          `hcl:"assert_file_is_executable,optional" systemd:"AssertFileIsExecutable"`
	AssertFileNotEmpty              string          `hcl:"assert_file_not_empty,optional" systemd:"AssertFileNotEmpty"`
	AssertFirstBoot                 string          `hcl:"assert_first_boot,optional" systemd:"AssertFirstBoot"`
	AssertGroup                     string          `hcl:"assert_group,optional" systemd:"AssertGroup"`
	AssertHost                      string          `hcl:"assert_host,optional" systemd:"AssertHost"`
	AssertIOPressure                string          `hcl:"assert_io_pressure,optional" systemd:"AssertIOPressure"`
	AssertKernelCommandLine         string          `hcl:"assert_kernel_command_line,optional" systemd:"AssertKernelCommandLine"`
	AssertKernelModuleLoaded        string          `hcl:"assert_kernel_module_loaded,optional" systemd:"AssertKernelModuleLoaded"`
	AssertKernelVersion             string          `hcl:"assert_kernel_version,optional" systemd:"AssertKernelVersion"`
	AssertMemory                    string          `hcl:"assert_memory,optional" systemd:"AssertMemory"`
	AssertMemoryPressure            string          `hcl:"assert_memory_pressure,optional" systemd:"AssertMemoryPressure"`
	AssertNeedsUpdate               string          `hcl:"assert_needs_update,optional" systemd:"AssertNeedsUpdate"`
	AssertOSRelease                 string          `hcl:"assert_os_release,optional" systemd:"AssertOSRelease"`
	AssertPathExists                string          `hcl:"assert_path_exists,optional" systemd:"AssertPathExists"`
	AssertPathExistsGlob            string          `hcl:"assert_path_exists_glob,optional" systemd:"AssertPathExistsGlob"`
	AssertPathIsDirectory           string          `hcl:"assert_path_is_directory,optional" systemd:"AssertPathIsDirectory"`
	AssertPathIsEncrypted           string          `hcl:"assert_path_is_encrypted,optional" systemd:"AssertPathIsEncrypted"`
	AssertPathIsMountPoint          string          `hcl:"assert_path_is_mount_point,optional" systemd:"AssertPathIsMountPoint"`
	AssertPathIsReadWrite           string          `hcl:"assert_path_is_read_write,optional" systemd:"AssertPathIsReadWrite"`
	AssertPathIsSymbolicLink        string          `hcl:"assert_path_is_symbolic_link,optional" systemd:"AssertPathIsSymbolicLink"`
	AssertSecurity                  string          `hcl:"assert_security,optional" systemd:"AssertSecurity"`
	AssertUser                      string          `hcl:"assert_user,optional" systemd:"AssertUser"`
	AssertVersion                   string          `hcl:"assert_version,optional" systemd:"AssertVersion"`
	AssertVirtualization            string          `hcl:"assert_virtualization,optional" systemd:"AssertVirtualization"`
	Before                          []hcl.Traversal `unitd:"before,optional" systemd:"Before"`
	BindTo                          []hcl.Traversal `unitd:"bind_to,optional" systemd:"BindTo"`
	BindsTo                         []hcl.Traversal `unitd:"binds_to,optional" systemd:"BindsTo"`
	CollectMode                     string          `hcl:"collect_mode,optional" systemd:"CollectMode"`
	ConditionACPower                string          `hcl:"condition_ac_power,optional" systemd:"ConditionACPower"`
	ConditionArchitecture           string          `hcl:"condition_architecture,optional" systemd:"ConditionArchitecture"`
	ConditionCPUFeature             string          `hcl:"condition_cpu_feature,optional" systemd:"ConditionCPUFeature"`
	ConditionCPUPressure            string          `hcl:"condition_cpu_pressure,optional" systemd:"ConditionCPUPressure"`
	ConditionCPUs                   string          `hcl:"condition_cp_us,optional" systemd:"ConditionCPUs"`
	ConditionCapability             string          `hcl:"condition_capability,optional" systemd:"ConditionCapability"`
	ConditionControlGroupController string          `hcl:"condition_control_group_controller,optional" systemd:"ConditionControlGroupController"`
	ConditionCredential             string          `hcl:"condition_credential,optional" systemd:"ConditionCredential"`
	ConditionDirectoryNotEmpty      string          `hcl:"condition_directory_not_empty,optional" systemd:"ConditionDirectoryNotEmpty"`
	ConditionEnvironment            string          `hcl:"condition_environment,optional" systemd:"ConditionEnvironment"`
	ConditionFileIsExecutable       string          `hcl:"condition_file_is_executable,optional" systemd:"ConditionFileIsExecutable"`
	ConditionFileNotEmpty           string          `hcl:"condition_file_not_empty,optional" systemd:"ConditionFileNotEmpty"`
	ConditionFirmware               string          `hcl:"condition_firmware,optional" systemd:"ConditionFirmware"`
	ConditionFirstBoot              string          `hcl:"condition_first_boot,optional" systemd:"ConditionFirstBoot"`
	ConditionGroup                  string          `hcl:"condition_group,optional" systemd:"ConditionGroup"`
	ConditionHost                   string          `hcl:"condition_host,optional" systemd:"ConditionHost"`
	ConditionIOPressure             string          `hcl:"condition_io_pressure,optional" systemd:"ConditionIOPressure"`
	ConditionKernelCommandLine      string          `hcl:"condition_kernel_command_line,optional" systemd:"ConditionKernelCommandLine"`
	ConditionKernelModuleLoaded     string          `hcl:"condition_kernel_module_loaded,optional" systemd:"ConditionKernelModuleLoaded"`
	ConditionKernelVersion          string          `hcl:"condition_kernel_version,optional" systemd:"ConditionKernelVersion"`
	ConditionMemory                 string          `hcl:"condition_memory,optional" systemd:"ConditionMemory"`
	ConditionMemoryPressure         string          `hcl:"condition_memory_pressure,optional" systemd:"ConditionMemoryPressure"`
	ConditionNeedsUpdate            string          `hcl:"condition_needs_update,optional" systemd:"ConditionNeedsUpdate"`
	ConditionOSRelease              string          `hcl:"condition_os_release,optional" systemd:"ConditionOSRelease"`
	ConditionPathExists             string          `hcl:"condition_path_exists,optional" systemd:"ConditionPathExists"`
	ConditionPathExistsGlob         string          `hcl:"condition_path_exists_glob,optional" systemd:"ConditionPathExistsGlob"`
	ConditionPathIsDirectory        string          `hcl:"condition_path_is_directory,optional" systemd:"ConditionPathIsDirectory"`
	ConditionPathIsEncrypted        string          `hcl:"condition_path_is_encrypted,optional" systemd:"ConditionPathIsEncrypted"`
	ConditionPathIsMountPoint       string          `hcl:"condition_path_is_mount_point,optional" systemd:"ConditionPathIsMountPoint"`
	ConditionPathIsReadWrite        string          `hcl:"condition_path_is_read_write,optional" systemd:"ConditionPathIsReadWrite"`
	ConditionPathIsSymbolicLink     string          `hcl:"condition_path_is_symbolic_link,optional" systemd:"ConditionPathIsSymbolicLink"`
	ConditionSecurity               string          `hcl:"condition_security,optional" systemd:"ConditionSecurity"`
	ConditionUser                   string          `hcl:"condition_user,optional" systemd:"ConditionUser"`
	ConditionVersion                string          `hcl:"condition_version,optional" systemd:"ConditionVersion"`
	ConditionVirtualization         string          `hcl:"condition_virtualization,optional" systemd:"ConditionVirtualization"`
	Conflicts                       []hcl.Traversal `unitd:"conflicts,optional" systemd:"Conflicts"`
	DefaultDependencies             bool            `hcl:"default_dependencies,optional" systemd:"DefaultDependencies"`
	Description                     string          `hcl:"description,optional" systemd:"Description"`
	Documentation                   string          `hcl:"documentation,optional" systemd:"Documentation"`
	FailureAction                   string          `hcl:"failure_action,optional" systemd:"FailureAction"`
	FailureActionExitStatus         string          `hcl:"failure_action_exit_status,optional" systemd:"FailureActionExitStatus"`
	IgnoreOnIsolate                 bool            `hcl:"ignore_on_isolate,optional" systemd:"IgnoreOnIsolate"`
	IgnoreOnSnapshot                string          `hcl:"ignore_on_snapshot,optional" systemd:"IgnoreOnSnapshot"`
	JobRunningTimeoutSec            string          `hcl:"job_running_timeout_sec,optional" systemd:"JobRunningTimeoutSec"`
	JobTimeoutAction                string          `hcl:"job_timeout_action,optional" systemd:"JobTimeoutAction"`
	JobTimeoutRebootArgument        string          `hcl:"job_timeout_reboot_argument,optional" systemd:"JobTimeoutRebootArgument"`
	JobTimeoutSec                   string          `hcl:"job_timeout_sec,optional" systemd:"JobTimeoutSec"`
	JoinsNamespaceOf                []hcl.Traversal `unitd:"joins_namespace_of,optional" systemd:"JoinsNamespaceOf"`
	OnFailure                       []hcl.Traversal `unitd:"on_failure,optional" systemd:"OnFailure"`
	OnFailureIsolate                bool            `hcl:"on_failure_isolate,optional" systemd:"OnFailureIsolate"`
	OnFailureJobMode                os.FileMode     `unitd:"on_failure_job_mode,optional" systemd:"OnFailureJobMode"`
	OnSuccess                       []hcl.Traversal `unitd:"on_success,optional" systemd:"OnSuccess"`
	OnSuccessJobMode                os.FileMode     `unitd:"on_success_job_mode,optional" systemd:"OnSuccessJobMode"`
	PartOf                          []hcl.Traversal `unitd:"part_of,optional" systemd:"PartOf"`
	PropagateReloadFrom             []hcl.Traversal `unitd:"propagate_reload_from,optional" systemd:"PropagateReloadFrom"`
	PropagateReloadTo               []hcl.Traversal `unitd:"propagate_reload_to,optional" systemd:"PropagateReloadTo"`
	PropagatesReloadTo              []hcl.Traversal `unitd:"propagates_reload_to,optional" systemd:"PropagatesReloadTo"`
	PropagatesStopTo                []hcl.Traversal `unitd:"propagates_stop_to,optional" systemd:"PropagatesStopTo"`
	RebootArgument                  string          `hcl:"reboot_argument,optional" systemd:"RebootArgument"`
	RefuseManualStart               bool            `hcl:"refuse_manual_start,optional" systemd:"RefuseManualStart"`
	RefuseManualStop                bool            `hcl:"refuse_manual_stop,optional" systemd:"RefuseManualStop"`
	ReloadPropagatedFrom            []hcl.Traversal `unitd:"reload_propagated_from,optional" systemd:"ReloadPropagatedFrom"`
	Requires                        []hcl.Traversal `unitd:"requires,optional" systemd:"Requires"`
	RequiresMountsFor               []string        `hcl:"requires_mounts_for,optional" systemd:"RequiresMountsFor"`
	RequiresOverridable             string          `hcl:"requires_overridable,optional" systemd:"RequiresOverridable"`
	Requisite                       []hcl.Traversal `unitd:"requisite,optional" systemd:"Requisite"`
	RequisiteOverridable            string          `hcl:"requisite_overridable,optional" systemd:"RequisiteOverridable"`
	SourcePath                      string          `hcl:"source_path,optional" systemd:"SourcePath"`
	StartLimitAction                string          `hcl:"start_limit_action,optional" systemd:"StartLimitAction"`
	StartLimitBurst                 uint64          `hcl:"start_limit_burst,optional" systemd:"StartLimitBurst"`
	StartLimitInterval              int             `hcl:"start_limit_interval,optional" systemd:"StartLimitInterval"`
	StartLimitIntervalSec           int             `hcl:"start_limit_interval_sec,optional" systemd:"StartLimitIntervalSec"`
	StopPropagatedFrom              []hcl.Traversal `unitd:"stop_propagated_from,optional" systemd:"StopPropagatedFrom"`
	StopWhenUnneeded                bool            `hcl:"stop_when_unneeded,optional" systemd:"StopWhenUnneeded"`
	SuccessAction                   string          `hcl:"success_action,optional" systemd:"SuccessAction"`
	SuccessActionExitStatus         string          `hcl:"success_action_exit_status,optional" systemd:"SuccessActionExitStatus"`
	SurviveFinalKillSignal          bool            `hcl:"survive_final_kill_signal,optional" systemd:"SurviveFinalKillSignal"`
	Upholds                         []hcl.Traversal `unitd:"upholds,optional" systemd:"Upholds"`
	Wants                           []hcl.Traversal `unitd:"wants,optional" systemd:"Wants"`
	WantsMountsFor                  []string        `hcl:"wants_mounts_for,optional" systemd:"WantsMountsFor"`
}
